---
# tasks file for webserver
- block:
  - name: Install Apache2
    yum:
      name: "{{ pkgname }}"
      state: latest

  - name: Create document root folder if not exist
    file:
      path: "{{ indexloc }}"
      state: directory
      owner: apache
      group: apache
      mode: 0755

  - name: Copy index page
    template:
      src: better_index.html
      dest: "{{ indexloc }}/index.html"
      owner: apache
      group: apache
      mode: 0755

  - name: Enable and Start Service
    service:
      name: httpd
      state: started
      enabled: true

  - name: Configure firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
  when: modus == 'install'

- block:
  - name: Remove Apache webserver software
    yum:
      name: "{{ pkgname }}"
      state: absent
  - name: Reset firewall
    firewalld:
      service: "{{ pkgport }}"
      state: disabled
      immediate: true
  when: modus == 'remove'

- block:
  - name: No actions
    debug:
      msg: "No action needed"
  when: modus == 'skipme'