---
- name: Install a webserver
  hosts: webservers

  vars:
    pkgname: httpd
    pkgservice: httpd
    pkgport: http
    indexloc: /var/www/html
    webpage_name: Ansible Tech Demo Webinar

  tasks:
    - name: Install Apache2
      yum:
        name: "{{ pkgname }}"
        state: latest

    - name: Create document root folder if not exist
      file:
        path: "{{ indexloc }}"
        state: directory
        owner: apache
        group: apache
        mode: 0755

    - name: Copy index page
      template:
        src: better_index.html
        dest: "{{ indexloc }}/index.html"
        owner: apache
        group: apache
        mode: 0755
    
    - name: Enable and Start Service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Configure firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

