---
- name: Install load balancer
  hosts: loadbalancers

  vars:
    pkgname: haproxy
    pkgservice: haproxy
    pkgfirewall: http
    pkgconfig: haproxy.cfg
    pkgconfigloc: /etc/haproxy/

  tasks:
    - name: HAProxy installed on loadbalancer vm 
      ansible.builtin.yum:
        name: "{{ pkgname }}"
        state: latest

    - name: HAProxy Configured 
      ansible.builtin.template:
        src: haproxy.cfg
        dest: "{{ pkgconfigloc }}{{ pkgconfig }}"
        owner: haproxy
        group: haproxy
        mode: 0644

    - name: HAProxy service Enabled and Started 
      ansible.builtin.service:
        name: "{{ pkgservice }}"
        state: started
        enabled: true

    - name: Firewalld Configured 
      ansible.posix.firewalld:
        service: "{{ pkgfirewall }}"
        state: enabled
        permanent: true
        immediate: true
    