---
- name: Install a webserver
  hosts: webservers
  become: true

  vars:
    pkgname: httpd
    pkgservice: httpd
    pkgport: http
    indexloc: /var/www/html
    webpage_name: Ansible Tech Demo Webinar

  tasks:
    - name: Apache2 installed on webservers
      ansible.builtin.yum:
        name: "{{ pkgname }}"
        state: latest

    - name: Created document root folder if not exist
      ansible.builtin.file:
        path: "{{ indexloc }}"
        state: directory
        owner: apache
        group: apache
        mode: 0755

    - name: index page Copied to document root 
      ansible.builtin.template:
        src: better_index.html
        dest: "{{ indexloc }}/index.html"
        owner: apache
        group: apache
        mode: 0755
    
    - name: Web Service Enabled and Started 
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Firewalld Configured 
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
