---
- name: Remove webserver software
  hosts: webservers

  vars:
    pkgname: httpd
    pkgservice: httpd
    pkgport: http
    indexloc: /var/www/html

  tasks:
    - name: Remove Apache webserver software
      ansible.builtin.yum:
        name: "{{ pkgname }}"
        state: absent


    - name: Reset firewall
      ansible.posix.firewalld:
        service: "{{ pkgport }}"
        state: disabled
        immediate: true

- name: test webserver removal
  hosts: localhost
  become: false

  tasks:
    - name: test if the webserver service is no longer providing an answer by a status code of -1 
      ansible.builtin.uri:
        url: http://myserverb
        status_code: -1