---
- name: Remove HAProxy from load balancer
  hosts: loadbalancers

  vars:
    pkgname: haproxy
    pkgservice: haproxy
    pkgfirewall: http
    pkgconfig: haproxy.cfg
    pkgconfigloc: /etc/haproxy/

  tasks:
    - name: Stop HAProxy service
      ansible.builtin.service:
        name: "{{ pkgservice }}"
        state: stopped

    - name: Reset firewall
      ansible.posix.firewalld:
        service: "{{ pkgfirewall }}"
        state: disabled
        permanent: true
        immediate: true

    - name: De-install HAProxy from loadbalancer 
      ansible.builtin.yum:
        name: "{{ pkgname }}"
        state: absent